import time
# Funções de Personagens
def heroi():
    print('(＾▽＾)')

def vilao():
    print('(｀皿´＃)')

def personagem():
    print('(◡‿◡ ♡) ')

def porco():
    print("(´• ω •`)ﾉ")

# Código do Jogo
print('*' * 10, 'Bem-vindo ao jogo "vida real"', '*' * 10)
print('Capítulo 1')
time.sleep(5)
print('-' * 20)
heroi()
print('Conheça seu personagem: é o Mike. Ele é apenas um cara genérico que gosta de animes e jogos de computador!')
print('-' * 20)
time.sleep(5)
print('-' * 20)
print('Mas um dia, sua vida mudou... drasticamente 🤯')
time.sleep(5)
print('Hoje, Mike acordou com batidas estranhas na sua porta...')
time.sleep(1)
print('Toc-toc')
time.sleep(1)
print('Quando Mike abriu a porta, ele encontrou uma pessoa desconhecida...')
print('-' * 20)
heroi()
print('/n')
vilao()
print('-' * 20)
time.sleep(3)
print('Mike: Quem é você?')
time.sleep(5)
print('Vilão: Eu sou aquele que está prestes a mudar sua vida...')
print('Vilão: Nós pegamos sua namorada...')
time.sleep(3)
print('A pessoa desapareceu assim que disse essas palavras')
time.sleep(5)
print('-' * 20)
heroi()
print('/n')
print('-' * 20)
time.sleep(5)

print('Capítulo 2: Emily')
time.sleep(5)
print('Assim que Mike ouviu sobre Emily, ele ficou absolutamente apavorado')
print('〣(ºΔº)〣')
time.sleep(5)
print('Emily era a velha amiga de Mike, e ele estava secretamente apaixonado por ela')
personagem()
time.sleep(3)
print('Agora Mike tem que parar sua maratona de Naruto e ir salvar Emily!')
time.sleep(5)
print('Mas será que ele consegue...?')
time.sleep(5)
print('Continua...')
print('ヘ(￣ω￣ヘ)    (〜￣△￣)〜   〜(￣▽￣〜)ヽ')

print("Capítulo 3: O capítulo Final!")
time.sleep(5)
print("Emily estava num escritório escuro na ilha de madagascar presa com 3 macacos.")
time.sleep(5)
print("Mike encontrou uma pista que seria crucial para descobrir onde Emily estava!")
time.sleep(2)
print("Na pista dizia: Sua amada está em Madagascar, uma ilha bem, bem, bem distante. Boa sorte para encontrála")
time.sleep(5)
print("Então Mike, juntamente com Lucas, seu amigo, vão buscar Emily!")
time.sleep(5)
print("Lucas e Mike foram comprar as passagens para poder ir para Madagascar, mas percebem que estão sem dinheiro! O que seria um problema beeeeeeem grande!!")
time.sleep(5)
print("Quando eles achavam que não poderia ficar pior, ficou pior (╬ʘ益ʘ╬)")
time.sleep(2)
print("Tinham cancelado todas as conexões de voo para Madagascar, o que iria dificultar muito os dois de irem salvar Emily")
time.sleep(5)
print("Quando Mike e Lucas ficaram sem esperanças, um porco voador apareceu!")
porco()
time.sleep(5)
print("O amigo porco ofereceu duas opções: 1 - O porco teria um jatinho particular para usar ou 2 - ele, que era um porco voador, ajudaria Lucas e Mike levando-os voando até Madagascar.")
time.sleep(5)
print("Lucas e Mike sem exitar escolhem que o porco levasse eles, e, em um piscar de olhos, os dois ja estavam na Ilha de Madagascar!")
time.sleep(5)
print("Os dois ficaram muito impressionados e agradeceram muito o porquinho por ter ajudado")
time.sleep(5)
print("Chegando lá, eles encontram um senhor idoso, sem teto que virou para os dois e disse: Senhores, eu sei quem vocês estão procurando e onde ela está.")
time.sleep(2)
print("Lucas e Mike ficaram muito animados e já foram perguntar onde estava Emily.")
time.sleep(5)
print("Mas o senhor disse: Mas tomem muito cuidado, pois a ilha toda está enfeitiçada, e isso pode acabar prejudicando vocês!")
time.sleep(5)
print("Quando a dupla olha pra trás e vé aquele mesmo porco, que os ajudou jogando poderes mágicos pela mão. Aquele mesmo porco que eles confiaram e chamaram de amigo.")
time.sleep(3)
print("Mike e seu amigo ficaram muito confusos querendo saber o que estava acontecendo.")
time.sleep(4)
print("Quando o porco disse: Fui eu, fui eu que amaldiçoei essa ilha, e vocês, bobos, cairam na minha armadilha!")
time.sleep(4)
print("Lucas e sua dupla correram enquanto tiveram tempo para salvar Emily.")
time.sleep(5)
print("Eles chegaram a tempo e conseguiram fazer com que Emily fosse salva.")
time.sleep(5)
print("Mas eles ainda tinham uma ilha inteira pra salvar!")
time.sleep(5)
print("Mike estava preparado para lutar com o porco mágico quando ouve: Mike, você ta bem? Eu acho que a bola acertou muito forte!")
time.sleep(3)
print("*Mike acorda* O que? O que aconteceu?")
time.sleep(4)
print('Lucas responde: Ué, você não se lembra? Você estava saindo de casa pra comprar um mangá quando o Luiz acertou a bola na sua cabeça.')
time.sleep(2)
print("*Mike resmunga* Ué, então foi tudo um sonho?")
time.sleep(2)
print("Lucas fica sem entender nada e pergunta à Mike: Que sonho?")
time.sleep(2)
print("Mike responde: Ah, deixa pra lá!")
time.sleep(5)

print('FIM!')
